### ISSUE TITLE
Unable to resolve module util from /home/react-native/uber/node_modules/camelize-ts/dist/index.js: util could not be found within the project.

### ISSUE THREAD

**Issue by yilmazbingo** [kbrabrand/camelize-ts#1]
"typescript": "^4.3.2"
            node --version : v14.15.1

I am getting above error in react-native. I follow those recommended steps:

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*

Problem still exists.

**Comment by kbrabrand** [comment]
I have not tested this in a web/RN context but `util` is being used for type checking - available in node only. 

I’m a bit swamped with work so can’t promise a date for when it’s fixed, but you’re more than welcome to propose a fix for it :pray:

**Comment by jonkoops** [comment]
This issue should be resolved now that `util` is no longer used in the code.

**Comment by jonkoops** [comment]
Ping @kbrabrand

**Comment by kbrabrand** [comment]
Thanks. Yes, the package no longer has any deps and it should be resolved. Please try the latest version if this is still something you need @yilmazbingo
