### ISSUE TITLE
Can't import module during testing.

### ISSUE THREAD

**Issue by doubleforte** [kbrabrand/camelize-ts#16]
Something is wrong with the distribution at https://www.npmjs.com/package/camelize-ts. (It was working fine on the older version, v1.0.8, but trying to update to v2.1 and sadness happened.)

The `dist/index.js` (broken) file looks like this:

```javascript
function camelCase(str) {
    return str.replace(/[_.-](\w|$)/g, function (_, x) {
        return x.toUpperCase();
    });
}
function walk(obj) {
    if (!obj || typeof obj !== "object")
        return obj;
    if (obj instanceof Date || obj instanceof RegExp)
        return obj;
    if (Array.isArray(obj))
        return obj.map(walk);
    return Object.keys(obj).reduce((res, key) => {
        const camel = camelCase(key);
        res[camel] = walk(obj[key]);
        return res;
    }, {});
}
export default function camelize(obj) {
    return typeof obj === "string" ? camelCase(obj) : walk(obj);
}
//# sourceMappingURL=index.js.map
```

But when I run my tests (Jest), I get errors from this package saying that I'm "trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript."

When I clone this repo and run `tsc scr/index.ts` I get the following (working) file, which is close to the `dist/` one, but not exact.

```javascript
"use strict"; // This line is missing from dist/
exports.__esModule = true; // This line is missing from dist/
function camelCase(str) {
    return str.replace(/[_.-](\w|$)/g, function (_, x) {
        return x.toUpperCase();
    });
}
function walk(obj) {
    if (!obj || typeof obj !== "object")
        return obj;
    if (obj instanceof Date || obj instanceof RegExp)
        return obj;
    if (Array.isArray(obj))
        return obj.map(walk);
    return Object.keys(obj).reduce(function (res, key) {
        var camel = camelCase(key);
        res[camel] = walk(obj[key]);
        return res;
    }, {});
}
function camelize(obj) { // This line has `export default` in dist/
    return typeof obj === "string" ? camelCase(obj) : walk(obj);
}
exports["default"] = camelize; // This line is missing from dist/
```

I don't know enough about publishing to npmjs.com to suggest how to fix it. Feels like something didn't go right with the compiler.

Great little package. Would love to be able to update to the latest version.

**Comment by jonkoops** [comment]
This is a known issue in Jest, for more information on how to deal with ES modules see [their documentation](https://jestjs.io/docs/ecmascript-modules) on this topic.

**Comment by jonkoops** [comment]
@kbrabrand could you close this one as it cannot be fixed on our end?
