### ISSUE TITLE
Non-recursive version

### ISSUE THREAD

**Issue by tonyxiao** [kbrabrand/camelize-ts#42]
Can we also support a non-recursive version of this? The use case is I'd like to transform database field names without transforming jsonb objects stored inside them.

**Comment by jonkoops** [comment]
Perhaps it would be possible to add a `depth` parameter to accomplish this. Feel free to open up a PR if you have some ideas.

**Comment by kbrabrand** [comment]
I have been thinking about this over the weekend, and was thinking of use cases. I was leaning towards doing it either shallowly (first level only) or recursive all the way down. Do you see a use case for doing `N` levels down, where `N` is some number between 1 and the depth of the structure you're transformin, @tonyxiao?

**Comment by tonyxiao** [comment]
I think either fully shallow or fully deep should be sufficient. Can typing even handle `n` level down?

**Comment by kbrabrand** [comment]
> [...] Can typing even handle `n` level down?

It would be tricky for sure, but whether or not it's _possible_ is something I'd have to investigate closer to answer..

**Comment by kbrabrand** [comment]
@tonyxiao & @jonkoops: see #43. Thoughts?

**Comment by tonyxiao** [comment]
Looks great!

**Comment by kbrabrand** [comment]
@tonyxiao A new release is out.
