### ISSUE TITLE
Camelize doesn't work when used on Arrays

### ISSUE THREAD

**Issue by LordZardeck** [kbrabrand/camelize-ts#47]
If you try to run Camelize on an array, it returns an incorrect type. We've had to write a helper to get around this issue:

```ts
import type { Camelize as CamelizeObject } from ‘camelize-ts’

type Camelize<T> = T extends (infer U)[] ? CamelizeObject<U>[] : CamelizeObject<T>
```

It would be nice if the library just did this on the `Camelize` type in the first place

**Comment by jonkoops** [comment]
Hi @LordZardeck, if you think there is a solid solution feel free to open up a PR!
